# Generated by Django 3.1.4 on 2021-01-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201231_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pet',
            name='contato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='pet',
            name='uf',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='UF'),
        ),
    ]
